Penneo/sdk-net

- Src/Penneo/(Model)/Document.cs
- Src/Penneo/(Model)/DocumentOption.cs
- Src/Penneo/Penneo.csproj
> DocumentOption - format is not correct #25

- Src/Penneo/(Model)/SignatureLine.cs
> Why is SignatureLine.SignedAt not hydrated? #32

- Src/Penneo/(Model)/Document.cs
- Src/Penneo/Mapping/MappingBuilder.cs
- Src/Penneo/Mapping/MethodProperties.cs
- Src/Penneo/PenneoConnector.cs
- Src/Penneo/Util/ReflectionUtil.cs
> Document SetPdf() method doesn't work #36

- .gitignore
- .travis.yml
- Src/Penneo/Penneo.csproj
- scripts/linux/install.sh
- scripts/linux/runtests.sh
> Unit tests using Travis and docker containers

- Src/Penneo/(Query)/Query.cs
> Use unix timestamps for filtering on dates #43

- docs/templates.md
The GetCaseFileTemplates() function has been deprecated
> Updated the documentation

- Src/Penneo/PenneoConnector.cs
> Assigning case file templates to case files #50

- Src/Penneo/(Model)/Folder.cs
> Fetching case files from folders

- Src/Penneo/(Model)/Folder.cs
- Src/PenneoTests/FolderTests.cs
- docs/folder.md
Fixes #58 
* Added functionality to link, unlink and list validations in folders
> Manipulating validations to folders

- docs/validation.md
The documentation doesn't explain how validation contents can be retrieved. Specially, what is retrieved when the validation process is in different statuses.
> Documentation about retrieving validation contents

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/(Model)/Document.cs
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/PenneoTests/Properties/AssemblyInfo.cs
> Release 1.2.1

- Src/Penneo/(Model)/Entity.cs
- Src/Penneo/Penneo.csproj
- Src/Penneo/RestConnector.cs
> Making rest calls directly to the server #57

- Src/Penneo/(Model)/SigningRequest.cs
- Src/Penneo/PenneoConnector.cs
> Set and update the parent of a folder #74

- Src/Penneo/(Model)/CaseFile.cs
- Src/Penneo/PenneoConnector.cs
> Specify a language for the case file #81

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/PenneoTests/Properties/AssemblyInfo.cs
> Release 1.4.1

- .gitignore
- Src/Penneo/(Query)/Query.cs
- Src/Penneo/Connector/WSSEAuthenticator.cs
- Src/Penneo/Penneo.csproj
- Src/Penneo/Util/PaginationUtil.cs
- Src/Penneo/packages.config
- Src/PenneoTests/PenneoTests.csproj
- Src/PenneoTests/packages.config
Support for RestSharp 105.2.3 - Not updated the NuGet package spec.
> Update to RestSharp 105.2.3

- Src/Penneo/(Model)/CaseFile.cs
- Src/Penneo/(Model)/Entity.cs
- Src/Penneo/Connector/ApiConnector.cs
- Src/Penneo/Connector/IApiConnector.cs
> Add properties to the Case File #98

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/PenneoTests/Properties/AssemblyInfo.cs
> Release 1.7.0

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/PenneoTests/Properties/AssemblyInfo.cs
> Release 2.0.0

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/PenneoTests/Properties/AssemblyInfo.cs
> Penneo file meta data

- CHANGELOG.md
- Src/Penneo/(Model)/Document.cs
- Src/Penneo/(Model)/Signer.cs
- Src/Penneo/Connector/ApiConnector.cs
- Src/Penneo/Info.cs
- Src/Penneo/Penneo.csproj
- Src/Penneo/PenneoSetup.cs
- Src/Penneo/Properties/AssemblyInfo.cs
- Src/Penneo/packages.config
- Src/PenneoTests/DocumentTests.cs
- Src/PenneoTests/PenneoTests.csproj
- Src/PenneoTests/packages.config
- docs/signer.md
- scripts/linux/install.sh
- scripts/linux/runtests.sh
Issues:
- could not run tests on linux
- using the api/v3 endpoint caused some problems reading documents
- we were still allowing people to use the old API endpoints
> Fix some issues

- CHANGELOG.md
- Src/Penneo/Penneo.csproj
> Add support for net46

- CHANGELOG.md
- Src/Penneo/(Model)/Signer.cs
> Fix not being able to read signer SSNs

- CHANGELOG.md
- Src/Penneo/Info.cs
For this PR that's already merged: https://github.com/Penneo/sdk-net/pull/133
> Prepare release 4.1.2

- CHANGELOG.md
- Nuget/Penneo.nuspec
- Src/Penneo/Penneo.csproj
- Src/PenneoTests/PenneoTests.csproj
The old version we have has a security issue.
> Upgrade RestSharp to 106.15.0

- Src/Penneo/(Model)/Contact.cs
- Src/Penneo/PenneoSetup.cs
- Src/PenneoTests/ContactTest.cs
Please accept and publish Nuget
> Added missing Contact endpoint including tests

- Src/Penneo/(Model)/Signer.cs
- Src/Penneo/PenneoSetup.cs
I've added the missing prop storeAsContact on the Signer model
> Add missing prop on Signer

- CHANGELOG.md
- Src/Penneo/(Model)/MessageTemplate.cs
- Src/Penneo/(Query)/Query.cs
- Src/Penneo/Info.cs
- Src/Penneo/Util/ReflectionUtil.cs
> Add missing options for getting default message templates

- CHANGELOG.md
- docs/signer.md
Adding an example of how to use the feature "Access Control with SMS"
> Update the signer documentation to show a usage of SMS

- CHANGELOG.md
- Src/Penneo/Connector/ApiConnector.cs
- Src/Penneo/Connector/WSSEAuthenticator.cs
- Src/Penneo/Penneo.csproj
- Src/PenneoTests/CaseFileTests.cs
- Src/PenneoTests/ContactTest.cs
- Src/PenneoTests/DocumentTests.cs
- Src/PenneoTests/FolderTests.cs
- Src/PenneoTests/KeyValueMetaDataTests.cs
- Src/PenneoTests/MappingTests.cs
- Src/PenneoTests/PaginationTests.cs
- Src/PenneoTests/PenneoTests.csproj
- Src/PenneoTests/QueryTests.cs
- Src/PenneoTests/SignatureLineTests.cs
- Src/PenneoTests/SignerTests.cs
- Src/PenneoTests/SigningRequestTests.cs
- Src/PenneoTests/TestUtil.cs
- Src/PenneoTests/ValidationTests.cs
Updating nuget packages to their last version. This solves this issue https://github.com/Penneo/sdk-net/issues/175
> Updating nuget packages
